name: Deploy Angular a GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta cada vez que subes algo a la rama  main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: Inyectar Secretos
        run: |
          sed -i "s|VALOR_A_REEMPLAZAR|${{ secrets.API_KEY_GEMINIS }}|g" src/environments/environment.prod.ts
          sed -i "s|VALOR_A_REEMPLAZAR|${{ secrets.API_KEY_GEMINIS }}|g" src/environments/environment.ts
          grep "apiKey" src/environments/environment.ts

      - name: Build de la aplicación
        run: npx ng build --configuration production --base-href /glosario/

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/glosario/browser

          branch: gh-pages




