name: Deploy Angular a GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta cada vez que subes algo a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # O la versión que uses
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci # Es más rápido y limpio que 'npm install' en entornos de CI

      # PASO CLAVE: Inyectar tus secretos antes de compilar
      - name: Inyectar Secretos
        run: |
          sed -i "s|API_KEY_GEMINIS|${{ secrets.API_KEY_GEMINIS }}|g" src/environments/environment.prod.ts

      - name: Build de la aplicación
        # Cambia 'nombre-de-tu-repo' por el nombre exacto de tu repositorio en GitHub
        run: ./node_modules/.bin/ng build --configuration production --base-href /glosario/

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/glosario/browser
          branch: gh-pages