name: Deploy Angular a GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta cada vez que subes algo a la rama  main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: Inyectar Secretos
        run: |
          mkdir -p src/environments
          # Creamos los dos archivos con la clave del secreto
          echo "export const environment = { production: true, apiKey: '${{ secrets.API_KEY_GEMINIS }}' };" > src/environments/environment.ts
          echo "export const environment = { production: true, apiKey: '${{ secrets.API_KEY_GEMINIS }}' };" > src/environments/environment.prod.ts
          
          echo "Archivos de configuraci贸n generados."
          # Verificaci贸n de seguridad en el log
          cat src/environments/environment.ts | grep "apiKey"

      - name: Build de la aplicaci贸n
        run: npx ng build --configuration production --base-href /glosario/

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/glosario/browser

          branch: gh-pages





